databases:
  - name: "cstadvert"
  - name: "cstauth"
  - name: "cstbasic"
  - name: "cstbinst"
  - name: "cstconsole"
  - name: "cstcustom"
  - name: "cstfund"
  - name: "cstgpt"
  - name: "cstim"
  - name: "cstlist"
  - name: "cstnacos"
  - name: "cstoauth"
  - name: "cstpresale"
  - name: "cstproperty"
  - name: "cstrent"
  - name: "cstseata"
  - name: "cstself"
  - name: "cstverify"
  - name: "cstwebpor"
  - name: "cstxxljob"
  - name: "gofastdfs"
  - name: "maclms"
backup_path: "./backups"
mysql:
  host: "192.168.31.222"
  port: 3306
  user: "root"
  password: "password"
#cron: "0 * * * * *"
cron: "0 0 2 * * *"
des: "备份数据库每天凌晨2点执行..."
clear: 3
