databases:
  - name: "database1"
  - name: "database2"
  - name: "database3"
  - name: "--all-databases" # 备份整个数据库
backup_path: "./backups"
mysql:
  host: "192.168.31.222"
  port: 3306
  user: "root"
  password: "password"
#cron: "0 0 2 * * *"
des: "备份数据库每天凌晨2点执行..."
#默认保留3天的备份文件，超过3天的备份文件将被自动删除
clear: 3
